autoviz_server:
  ros__parameters:
    host_ip: "0.0.0.0"
    port: 39090
    max_clients: 8
    publish_rate_hz: 20
    topic_timeout_ms: 5000
    vehicle_length_m: 4.9
    vehicle_width_m: 1.95
    wheel_base_m: 2.85
    topics:
      location: "/location"
      obstacles: "/targets/final_objects"
      range_motion_request: "/detection/range_motion_request"
      inspection_request_goal: "/detection/inspection_request_goal"
      control_command: "/chassis_command"
      chassis_state: "/chassis_states"
      action_state: "/system_run_states"
      task_state: "/task_params"
      local_path: "/local_path"
      global_path: "/global_path"
      depth_action_status: "/depth_command_action/_action/status"
      depth_action_feedback: "/depth_command_action/_action/feedback"
      move_action_status: "/move_action/_action/status"
      move_action_feedback: "/move_action/_action/feedback"
